
@start_url = http://localhost:3000

###
GET {{start_url}}/api/hello

###
GET {{start_url}}/api/hello/jeremy

###
GET {{start_url}}/api/date

###
POST {{start_url}}/api/auth/signin

###
POST {{start_url}}/api/auth/signout